version: "3.7"
volumes:
    mysqldata: ~
    pgsql_data: ~

services:
    app:
        build:
            args:
                user: devBarathon
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: barathon-app
        image: eddymandran/barathon-docker
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - barathon

#    db:
#        image: mysql:8.0
#        container_name: barathon-mysql
#        restart: unless-stopped
#        environment:
#            MYSQL_DATABASE: ${DB_DATABASE}
#            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#            MYSQL_PASSWORD: ${DB_PASSWORD}
#            MYSQL_USER: ${DB_USERNAME}
#            SERVICE_TAGS: dev
#            SERVICE_NAME: mysql
#        volumes:
#            - mysqldata:/docker-entrypoint-initdb.d
#        networks:
#            - barathon

    dbpgsql:
        image: postgres:14
        container_name: barathon-pgsql
        restart: unless-stopped
        volumes:
            - pgsql_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "54320:5432"
        networks:
            - barathon

    nginx:
        image: nginx:alpine
        container_name: barathon-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - barathon

networks:
    barathon:
        driver: bridge
