version: "3.7"
volumes:
    mysqldata: ~
    pgsql_data: ~
    pgadmin-data: ~

services:
# Laravel Service
    app:
        build:
            args:
                user: devBarathon
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: barathon-app
        image: eddymandran/barathon-docker
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - barathon

# Mysql Service
#    db:
#        image: mysql:8.0
#        container_name: barathon-mysql
#        restart: unless-stopped
#        environment:
#            MYSQL_DATABASE: ${DB_DATABASE}
#            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#            MYSQL_PASSWORD: ${DB_PASSWORD}
#            MYSQL_USER: ${DB_USERNAME}
#            SERVICE_TAGS: dev
#            SERVICE_NAME: mysql
#        volumes:
#            - mysqldata:/docker-entrypoint-initdb.d
#        networks:
#            - barathon

# PhpMyAdmin Service
#    phpmyadmin:
#        image: phpmyadmin
#        container_name: pma_barathon-mysql
#        links:
#            - db
#        environment:
#            PMA_HOST: mysql
#            PMA_PORT: 3306
#            PMA_ARBITRARY: 1
#        restart: always
#        ports:
#            - "8085:80"
#        networks:
#            - barathon

# Postgres Service
    dbpgsql:
        image: postgres:14
        container_name: barathon-pgsql
        restart: unless-stopped
        volumes:
            - pgsql_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "54320:5432"
        networks:
            - barathon

# PgAdmin Service
    pgadmin:
        container_name: pgadmin4_barathon-pgsql
        image: dpage/pgadmin4
        restart: always
        links:
            - dbpgsql
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        networks:
            - barathon

    # Nginx Service
    nginx:
        image: nginx:alpine
        container_name: barathon-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - barathon

networks:
    barathon:
        driver: bridge
